### ISSUE TITLE
sqlite.db文件路径在 user/Appdata/keli/ 内

### ISSUE THREAD

**Issue by liooooo29** [Lukrisum/keli-todo#6]
是否可以自定义一个命令让用户修改存在路径

**Comment by Lukrisum** [comment]
> 是否可以自定义一个命令让用户修改存在路径

good proposal 👌

**Comment by Lukrisum** [comment]
> 最新的版本（目前是 `^0.3.3`）已经支持该功能，请使用 `$ keli init` 命令。
>  this feature is available in the latest version ( now `^0.3.3`)，just use the command `$ keli init` .
